import type { DemoBook } from './types';
import originals from './english-public-domain.json';

const branch = (text: string) => `Demo branch — not the original text.\n\n${text}`;

export const englishClassics: DemoBook[] = [
  {
    id:'demo-austen',locale:'en',title:'Pride and Prejudice',author:'Jane Austen · Public domain',
    tags:['Classic','Social comedy','Romance','Public domain'],
    summary:'An eligible neighbour, a disastrous first impression, and a room full of people keeping score. The complete opening six chapters, with alternative conversations to explore the distance between wit and understanding.',
    chapters:originals['demo-austen'].chapters.map((c,i)=>({...c,summary:[
      'News of Bingley’s tenancy at Netherfield makes Mrs Bennet demand a visit; her husband turns the conversation into a private joke.',
      'Mr Bennet reveals that he has already visited Bingley, having enjoyed his family’s uncertainty.',
      'At the assembly, Bingley admires Jane. Darcy dismisses Elizabeth within her hearing, and she makes the slight into a story.',
      'Jane and Elizabeth assess the newcomers differently; Bingley’s confidence depends partly on Darcy’s judgement.',
      'The Lucas family discusses the assembly, distinguishing pride from vanity while Elizabeth’s grievance hardens.',
      'Charlotte advises Jane to display affection. Darcy begins to admire Elizabeth, who refuses his offer to dance without knowing his changed opinion.',
    ][i]})),
    characters:[
      {name:'Elizabeth Bennet',aliases:['Elizabeth','Lizzy','Eliza'],role:'Second Bennet daughter and acute observer',goal:'Keep her judgement and independence in a marriage-minded society',trait:'Witty, perceptive, quick to form an opinion',note:'Hears Darcy’s slight at the assembly; does not yet know that his opinion of her is changing.',voice:'Light irony, precise challenges, amusement that can conceal hurt.'},
      {name:'Fitzwilliam Darcy',aliases:['Darcy','Mr. Darcy'],role:'Bingley’s wealthy friend',goal:'Choose company on his own demanding terms',trait:'Reserved, proud, increasingly curious',note:'His public discourtesy precedes his private appreciation of Elizabeth; the opening offers no reconciliation.',voice:'Formal, economical, awkward when required to explain a feeling.'},
      {name:'Jane Bennet',aliases:['Jane'],role:'Eldest Bennet daughter',goal:'Think well of others while navigating her attraction to Bingley',trait:'Kind, modest, slow to condemn',note:'Her composure creates uncertainty about the depth of her interest.',voice:'Generous interpretations without Elizabeth’s barbed humour.'},
      {name:'Charles Bingley',aliases:['Bingley','Mr. Bingley'],role:'New tenant of Netherfield',goal:'Enjoy society and see Jane again',trait:'Warm, sociable, susceptible to trusted opinions',note:'He admires Jane openly and finds more to like at the assembly than Darcy does.',voice:'Ready enthusiasm and friendly invitations.'},
      {name:'Charlotte Lucas',aliases:['Charlotte','Miss Lucas'],role:'Elizabeth’s practical friend',goal:'Understand the material chances behind romantic appearances',trait:'Pragmatic, observant, unsentimental',note:'Advises that Jane make her interest visible; no later marriage is assumed in this excerpt.',voice:'Calm propositions that expose an uncomfortable social bargain.'},
      {name:'Mrs Bennet',aliases:['Mrs. Bennet'],role:'Mother of five daughters',goal:'Secure advantageous marriages for her daughters',trait:'Anxious, enthusiastic, indiscreet',note:'Treats a wealthy new neighbour as an immediate family opportunity.',voice:'Emphatic certainty followed by complaints about her nerves.'},
      {name:'Mr Bennet',aliases:['Mr. Bennet'],role:'Father of the Bennet sisters',goal:'Protect his own amusement and quiet',trait:'Dry, detached, fond of teasing',note:'His early visit reveals the kindness and evasiveness within the same joke.',voice:'Understatement that lets another speaker discover the punchline.'},
      {name:'Caroline Bingley',aliases:['Miss Bingley'],role:'Bingley’s socially ambitious sister',goal:'Control access to her circle and Darcy’s attention',trait:'Polished, selective, competitive',note:'Mocks Elizabeth’s family when Darcy admits admiring her eyes.',voice:'Elegant compliments with social exclusions concealed inside.'},
    ],
    relations:[
      {from:0,to:1,label:'A slight overheard',status:'strained',note:'Elizabeth hears Darcy refuse to dance with her; his later curiosity is not mutual knowledge.',chapter:3},
      {from:2,to:3,label:'Visible interest, private hopes',status:'active',note:'Bingley dances with Jane twice; her sisters and neighbours interpret the preference.',chapter:3},
      {from:0,to:2,label:'Affectionate disagreement',status:'active',note:'The sisters differ over how generously to judge the Bingley family.',chapter:4},
      {from:0,to:4,label:'Wit meets pragmatism',status:'active',note:'Charlotte distinguishes feeling affection from making it visible.',chapter:6},
      {from:1,to:3,label:'Friendship with unequal influence',status:'active',note:'Bingley trusts Darcy’s judgement despite their contrasting social temperaments.',chapter:4},
      {from:5,to:6,label:'Domestic misdirection',status:'strained',note:'Mr Bennet conceals his visit while Mrs Bennet worries about securing an introduction.',chapter:2},
      {from:7,to:1,label:'Attention and social policing',status:'active',note:'Miss Bingley answers Darcy’s interest in Elizabeth with ridicule of her family.',chapter:6},
    ],
    world:[
      {title:'Netherfield',type:'location',content:'Bingley’s rented estate; its availability is news with immediate social consequences.'},
      {title:'Longbourn',type:'location',content:'The Bennet family home, where private conversations interpret public encounters.'},
      {title:'An introduction',type:'rule',content:'An established acquaintance makes visits possible; the father’s visit becomes a scarce family resource.'},
      {title:'Two dances',type:'rule',content:'Repeated attention at an assembly invites everyone to infer a preference.'},
      {title:'Annual income',type:'rule',content:'Reported wealth shapes how strangers are assessed before their conduct is known.'},
      {title:'Lucas Lodge',type:'location',content:'Neighbourly sociability gives Darcy and Elizabeth a second occasion to misunderstand one another.'},
    ],
    outlines:[
      {title:'The neighbourhood keeps score',type:'main',summary:'Money, visits and dances establish the social field before mutual understanding can develop.',chapters:[1,2,3]},
      {title:'A judgement becomes a story',type:'conflict',summary:'Darcy’s slight supplies Elizabeth with an entertaining account that reinforces her opinion.',chapters:[3,5,6]},
      {title:'How much should affection show?',type:'side',summary:'Jane’s reserve, Bingley’s openness and Charlotte’s advice form competing social strategies.',chapters:[3,4,6]},
      {title:'Unequal knowledge',type:'foreshadow',summary:'Darcy notices Elizabeth while she still believes he finds her merely tolerable.',chapters:[3,6]},
    ],
    source:{url:originals['demo-austen'].ebook,note:'Jane Austen (1813). Complete chapters I–VI from Project Gutenberg ebook 1342. Original English, with print-line wrapping and illustration markers removed. Demo branches are new fiction, not Austen text.'},
    scenario:{chapter:3,sourceText:'“She is tolerable: but not handsome enough to tempt me;',
      instruction:'Demo branch: let Elizabeth address the slight while Darcy is still able to correct it. Keep the embarrassment social, not melodramatic.',
      rewriteText:branch('“Tolerable is a useful recommendation, sir,” said Elizabeth, turning before Bingley could rescue his friend. “It sets expectations at a height one might reasonably exceed.”\n\nDarcy looked at her. He had prepared no response for a young lady who had heard him accurately.\n\n“I spoke with insufficient consideration.”\n\n“For my hearing, certainly.”\n\nBingley found the musicians suddenly deserving of his whole attention.'),
      continueText:branch('Darcy offered a dance. Elizabeth declined it with a civility he could not mistake for gratitude.\n\n“I should dislike to make an apology so expensive.”\n\nHe bowed. For the remainder of the evening, he was less certain that silence would improve his reputation; Elizabeth was less certain that he could not blush.'),
      whatIfText:branch('An immediate challenge obliges Darcy to acknowledge the insult. Elizabeth retains her offence, but her account now includes an awkward apology. Their disagreement becomes specific enough to revisit rather than a settled verdict about his character.'),
      futureText:branch('At Lucas Lodge, Elizabeth found Darcy listening.\n\n“Are you collecting further evidence against the neighbourhood?”\n\n“I had thought to correct my first impressions.”\n\n“That is a considerable undertaking. I shall not interrupt it by telling you which corrections to make.”\n\nWhen Sir William proposed a dance, she still refused. But this time she addressed Darcy directly, and he asked whether she preferred conversation. It was a modest improvement, which neither was disposed to advertise.'),
      bridge:'A public slight receives a direct reply; Darcy apologises without securing a dance; Elizabeth’s story gains an inconvenient qualification; at Lucas Lodge both can refer to an encounter they actually shared.',
      titles:{rewrite:'An insult within hearing',continue_block:'An expensive apology',what_if:'What if Elizabeth answers at once?',future_jump:'A correction at Lucas Lodge',roleplay_session:'The cost of tolerable'},
      delta:{before:'A verdict formed without a conversation',after:'An offence acknowledged, not yet forgiven',description:'Neither attraction nor forgiveness is assumed. A specific apology creates room for another exchange.'},
      roleplay:{opening:'Do you always offer your opinions where their subjects may conveniently hear them?',reply:'Not intentionally. I begin to suspect that this does little to recommend the practice.',narration:'Darcy draws himself up, then appears to reconsider whether an additional inch will assist him.',responses:['You are entitled to think me uncivil. I should prefer to supply less evidence for the opinion.','If I offer a dance now, you will reasonably suppose that I am seeking an easy conclusion to a difficult conversation.','I cannot recall the words. I can only take greater care that my next ones deserve to be heard.']},
      alternative:{title:'What if Charlotte arranges the introduction?',instruction:'Demo branch: have a practical friend change the setting of a first conversation without manufacturing attraction.',text:branch('Charlotte placed Elizabeth beside Darcy on the reasonable pretext of settling a question about the music. Neither could escape without appearing discourteous to their hostess. Elizabeth answered the question, Darcy asked another, and Charlotte withdrew before either discovered that the first had required no settlement at all.')},
    },
    skill:{title:'Let wit carry a social wound',rule:'Give a character a joke that both protects their pride and narrows their judgement. Let a later exchange complicate the joke without immediately curing the hurt.',avoid:'Turning a guarded apology into instant affection'},
  },
  {
    id:'demo-dracula',locale:'en',title:'Dracula',author:'Bram Stoker · Public domain',
    tags:['Classic','Gothic horror','Epistolary','Public domain'],
    summary:'A solicitor goes abroad for a routine property transaction. His host has no reflection, the doors are locked, and the letters home acquire a terrifying timetable. Complete chapters I–IV of Jonathan Harker’s journal.',
    chapters:originals['demo-dracula'].chapters.map((c,i)=>({...c,summary:[
      'Jonathan travels toward the Count’s castle, recording meals and local warnings before a disturbing carriage journey.',
      'The Count questions Jonathan about England. A shaving accident and a missing reflection expose the rules beneath the welcome.',
      'Jonathan sees the Count crawl down the castle wall, discovers the absence of servants, and encounters three threatening women.',
      'Forced letters establish a false timetable. Failed messages, the Count’s stolen disguise and the earth-filled boxes confirm Jonathan’s imprisonment.',
    ][i]})),
    characters:[
      {name:'Jonathan Harker',aliases:['Jonathan','Harker'],role:'English solicitor keeping a private journal',goal:'Survive captivity and carry reliable evidence home',trait:'Methodical, polite, increasingly desperate',note:'Records dates and observations to resist his host’s control of the story.',voice:'Precise diary observations punctuated by appeals to sanity and to Mina.'},
      {name:'Count Dracula',aliases:['Count','Dracula'],role:'Aristocratic host preparing to travel to England',goal:'Control his guest’s knowledge and outward correspondence',trait:'Ceremonious, patient, possessive',note:'Has no reflection, moves along walls and uses Jonathan’s clothes; his account of hospitality conceals captivity.',voice:'Elaborate courtesy that becomes a command without changing its form.'},
      {name:'Mina Murray',aliases:['Mina'],role:'Jonathan’s fiancée, absent from the castle',goal:'Remain connected through the correspondence Jonathan hopes to send',trait:'Known here through Jonathan’s affection and hopes',note:'These chapters give no independent Mina viewpoint. References to her represent what Jonathan remembers or imagines.',voice:'No invented canonical dialogue; invoked as the intended reader of a future account.'},
      {name:'Peter Hawkins',aliases:['Mr. Hawkins','Hawkins'],role:'Solicitor who sent Jonathan on the assignment',goal:'Complete his client’s English property business',trait:'Professional, trusting of the apparent transaction',note:'The Count uses the employer’s letter to frame Jonathan’s visit as ordinary business.',voice:'Formal business correspondence; not an eyewitness to the castle.'},
      {name:'The innkeeper’s wife',aliases:['old lady'],role:'Local woman who warns Jonathan before his journey',goal:'Prevent him from travelling on a dangerous night',trait:'Fearful, insistent, compassionate',note:'Gives him a crucifix he initially interprets through his own prejudices.',voice:'Urgent warnings across an imperfectly shared language.'},
      {name:'The three women',aliases:['three young women','three women'],role:'Dangerous inhabitants of the castle',goal:'Approach the unprotected visitor',trait:'Alluring, predatory, resentful of the Count’s control',note:'The Count interrupts their approach; their freedom and his claims expose another hierarchy inside the prison.',voice:'Intimate speech made threatening by its context.'},
    ],
    relations:[
      {from:0,to:1,label:'Hospitality becomes confinement',status:'strained',note:'Locked doors and the shaving incident undermine the language of welcome.',chapter:2},
      {from:0,to:2,label:'A future reader worth surviving for',status:'active',note:'Jonathan’s concern for Mina gives the private journal a destination beyond himself.',chapter:4},
      {from:0,to:3,label:'Professional duty exploited',status:'active',note:'The employer’s introduction provides an apparently respectable reason to remain.',chapter:2},
      {from:0,to:4,label:'A warning understood too late',status:'active',note:'The gift at departure later acquires significance Jonathan could not initially accept.',chapter:1},
      {from:0,to:5,label:'Curiosity meets predation',status:'strained',note:'Sleeping beyond the safe rooms exposes Jonathan to a danger the host had warned him against.',chapter:3},
      {from:1,to:5,label:'A contested claim',status:'strained',note:'The Count asserts control over their access to his guest.',chapter:3},
      {from:1,to:3,label:'Respectable client, hidden purpose',status:'hidden',note:'Property documents and an employer’s endorsement conceal the host’s intentions.',chapter:2},
    ],
    world:[
      {title:'Castle Dracula',type:'location',content:'An apparently inhabited estate with no ordinary servants and no usable exit for its guest.'},
      {title:'The shaving glass',type:'item',content:'A mundane mirror supplies an observable contradiction, then the Count destroys it.'},
      {title:'The crucifix',type:'item',content:'A gift accepted with unease becomes a source of protection during the shaving incident.'},
      {title:'The journal',type:'item',content:'Private dated observations preserve a chronology against the host’s dictated account.'},
      {title:'Letters with future dates',type:'rule',content:'Forced correspondence manufactures evidence that Jonathan remained alive and free at times chosen by his captor.'},
      {title:'The boxes of earth',type:'item',content:'Cargo and a hiding place; their movement links the closed castle to travel beyond it.'},
      {title:'Carfax',type:'location',content:'The English property transaction supplies a respectable route out of Transylvania for the Count.'},
    ],
    outlines:[
      {title:'A business trip loses its ordinary explanations',type:'main',summary:'Travel notes become an inventory of anomalies, then a record of imprisonment.',chapters:[1,2,3,4]},
      {title:'Evidence is fragile',type:'conflict',summary:'The mirror is destroyed and correspondence controlled; Jonathan must preserve what he can establish.',chapters:[2,4]},
      {title:'Courtesy as coercion',type:'foreshadow',summary:'Invitations, warnings and requests reveal themselves as rules the visitor cannot refuse.',chapters:[2,3,4]},
      {title:'Who controls the date?',type:'climax',summary:'The dictated letters turn a timetable into an implied sentence, making escape urgent.',chapters:[4]},
    ],
    source:{url:originals['demo-dracula'].ebook,note:'Bram Stoker (1897). Complete chapters I–IV from Project Gutenberg ebook 345. Original English, with print-line wrapping and plain-text italic markers removed. Historical wording retained. Demo branches are new fiction, not Stoker text.'},
    scenario:{chapter:2,sourceText:'It is a foul bauble of man’s vanity. Away with it!',
      instruction:'Demo branch: let Jonathan conceal one shard of the shattered mirror. Make the evidence useful but dangerous, without granting him knowledge beyond these four chapters.',
      rewriteText:branch('8 May.—When the Count turned from the window, I bent as though to retrieve my razor. A splinter of the glass had caught in the fold of my towel. I closed the cloth upon it before he could see.\n\nHe asked whether I had cut myself. I answered that I had been careless. Both statements, I reflected afterwards, could have been true.\n\nI have put the fragment between two pages of this book. It reflects the candle plainly. I am ashamed to write how long I sat waiting for it to do otherwise.'),
      continueText:branch('9 May.—I cannot carry the glass openly, nor can I leave it where my host may find it. At breakfast I heard his step behind me and nearly laid my hand upon the pocket that contained it.\n\nIt is an extraordinary thing to discover that proof may make a man less safe. Yesterday I feared that I had imagined what I saw. Today I must ensure that he does not know I saw it.'),
      whatIfText:branch('Jonathan preserves a fragment and gains repeatable evidence of the missing reflection. Concealment demands more care, while the Count’s control of doors and correspondence remains intact. Evidence improves the record, not the chances of being believed without escape.'),
      futureText:branch('30 June.—I have wrapped the glass in the page bearing the dates of the three letters. If this book is found, the reader may test the one claim and judge the other against it.\n\nThere is no comfort in having assembled a persuasive account of one’s own disappearance. Yet arranging these things has steadied my hands. I shall need them steady on the wall.\n\nMina, if I have mistaken everything, forgive the terror with which I have written it. If I have not, let no one persuade you that I left this place willingly.'),
      bridge:'A hidden shard preserves the anomaly; Jonathan tests it cautiously; the forced letters remain a second, independent clue; at the final window he packages both observations for a possible reader before attempting escape.',
      titles:{rewrite:'A shard in the towel',continue_block:'The danger of keeping proof',what_if:'What if Harker saves the glass?',future_jump:'Evidence at the final window',roleplay_session:'A courteous request to leave'},
      delta:{before:'A destroyed observation and growing self-doubt',after:'Concealed evidence under constant risk of discovery',description:'Jonathan gains a physical test, but no new power, safe exit or supernatural expertise.'},
      roleplay:{opening:'My work is nearly complete, Count. I should like to write Mr Hawkins with the date of my departure.',reply:'Then we shall choose a date which will spare your good employer needless uncertainty. You see how carefully I attend to your affairs.',narration:'The Count lays three sheets of paper beside the ink. Jonathan notices that none has yet been dated.',responses:['You must not mistake my concern for an obstacle, my friend. The roads are difficult for one who does not know them.','Write that you are well. It is the first thing those who love us wish to read, and surely the kindest thing to tell them.','Departure is a small word for an undertaking with so many arrangements. Tonight we shall attend to the letters. Tomorrow, perhaps, to the rest.']},
      alternative:{title:'What if he refuses the dictated dates?',instruction:'Demo branch: expose the threat beneath courtesy without making defiance an effortless escape.',text:branch('I left the dates blank. The Count read each sheet and set it down with exquisite care. “An oversight,” he said. I answered that I did not know on which day I should be free to travel. For the first time since my arrival, he permitted the silence to become openly hostile.')},
    },
    skill:{title:'Turn an ordinary document into a threat',rule:'Establish a practical record, then let an antagonist control one of its ordinary details. A date or signature can imply a terrible future without stating it.',avoid:'Explaining every supernatural rule before the witness can observe it'},
  },
];
