import type { BookProgression } from './progression-types';

export const classicProgression: Record<string, BookProgression> = {
  'demo-monkey': {
    characters: {
      0: [[1,'有名无职的齐天大圣','受封弼马温后因官微反天；再被招安，得到齐天大圣空衔。','只是加他个空衔'],[2,'反天归山的齐天大圣','偷桃、饮酒、盗丹后返回花果山，天兵围山。','先偷桃，后偷酒'],[3,'被擒的齐天大圣','与二郎神斗变，遭金刚琢击中，被天兵擒获。','绳索捆绑'],[4,'五行山下的孙悟空','八卦炉中炼出火眼金睛，出炉再闹天宫；与如来赌赛失败，被压五行山。','五行山']],
      1: [[1,'两度招安的使者','先引猴王入天庭，再以齐天大圣空衔化解兵戈；实际待遇仍未解决。','金星']],
      2: [[1,'以封号安抚猴王的玉帝','接受招安建议，授有名无职的齐天大圣名号。','大圣'],[2,'下令围剿的玉帝','蟠桃宴与丹药被毁，派兵捉拿孙悟空。','玉帝'],[3,'接收擒猴战果的玉帝','悟空被擒，天庭暂获胜利。','玉帝'],[4,'求助如来的玉帝','八卦炉失败后天宫再乱，最终由如来制止。','如来']],
      3: [[3,'奉调擒猴的二郎神','与悟空斗法变化，借老君法器之助擒住对手。','二郎']],
      4: [[2,'丹药被盗的老君','发现仙丹被悟空偷吃，向天庭报告。','老君'],[3,'以金刚琢助战的老君','从空中投下法器，改变斗法局势。','金钢'],[4,'炼化失败的老君','八卦炉未能炼死悟空，反被踢翻，危机升级。','八卦炉']],
      5: [[4,'以掌中赌赛降猴的如来','悟空误认能逃出手掌，赌败后被压五行山。','五行山']],
      6: [[2,'奉命采桃的七衣仙女','告知蟠桃会没有邀请齐天大圣，成为悟空发怒的直接诱因。','仙女']],
    },
    relations: {
      0: [[1,'两次招安','金星用官职劝猴王归顺，封号尚未带来实质职权。','金星']],
      1: [[1,'受封与空衔','悟空接受齐天大圣之号，天庭以名位安抚冲突。','只是加他个空衔'],[2,'反天与围剿','蟠桃宴受辱引发偷桃盗丹，玉帝派兵围山。','玉帝','strained'],[3,'被擒与问罪','悟空被押回天庭，双方力量暂时失衡。','擒','strained'],[4,'反抗被镇压','悟空出炉再闹天宫，玉帝求助如来后冲突结束。','如来','resolved']],
      2: [[3,'斗法后被擒','二郎神追逐斗变，最终借法器助力擒住悟空。','二郎','strained']],
      3: [[2,'盗丹之怨','悟空偷吃老君仙丹。','老君','strained'],[3,'法器助擒','老君用金刚琢打中悟空。','金钢','strained'],[4,'炼化失败','八卦炉未杀悟空，他出炉后踢翻炉子。','八卦炉','strained']],
      4: [[4,'赌败与镇压','悟空未能越出如来手掌，被压五行山。','五行山','resolved']],
      5: [[2,'名单外的大圣','仙女按名单答复，悟空发现空衔不等于获邀。','仙女','strained']],
      6: [[1,'采纳招安建议','玉帝听从金星，以官职降低争斗成本。','金星']],
      7: [[3,'协力擒猴','二郎斗变之际，老君金刚琢助擒。','金钢']],
    },
    world: {
      0: [[1,'猴王初入天庭受阻，天门准入与身份名位相连。','南天门']],
      1: [[1,'有名无职的安抚性封号，悟空暂时接受。','只是加他个空衔'],[2,'蟠桃会不列其名，空衔与实际待遇的矛盾引爆。','蟠桃']],
      2: [[2,'悟空受命看管后偷食蟠桃；采桃仙女揭示他并无宴会请帖。','蟠桃']],
      3: [[3,'老君投出的法器击中悟空，帮助二郎神完成擒拿。','金钢']],
      4: [[4,'悟空在炉中未死，得火眼金睛后逃出；炼化手段反使天宫危机加重。','八卦炉']],
      5: [[4,'如来翻掌化山，悟空被压其下，失去行动自由。','五行山']],
      6: [[4,'悟空以为已飞到天边，实际仍在如来手掌之内；误判边界导致赌败。','手掌']],
    },
  },
  'demo-redcliff': {
    characters: {
      0: [[1,'出使东吴的刘备谋士','舌战群儒，促使孙权考虑联合抗曹。','孔明'],[2,'激周瑜抗曹的谋士','以二乔之说激将，联盟建立但周瑜已对其才能起忌。','二乔'],[4,'完成草船借箭的盟友','三日内借曹军箭支完成限期任务，仍须防备周瑜。','箭'],[7,'借东风后脱身的谋士','设坛候风后离开吴营；火攻条件齐备。','东风'],[8,'布置伏兵的军师','预判曹操退路，令关羽把守华容并处理其放曹后的军令责任。','华容']],
      1: [[2,'受命抗曹的大都督','主张与曹军决战，获孙权授兵；对孔明兼有合作与戒心。','周瑜'],[3,'施反间计的统帅','借蒋干盗书使曹操误杀水军将领。','蒋干'],[4,'组织苦肉诈降的统帅','借箭试探失败，与黄盖约定苦肉计。','黄盖'],[7,'发动赤壁火攻的统帅','东风已至，黄盖火船突入曹军，连锁战船起火。','火']],
      2: [[1,'威胁江东的北方统帅','南下兵势使江东争论降战；结果尚未确定。','曹操'],[3,'误杀水军将领的统帅','相信蒋干带回的伪信，杀蔡瑁张允后才意识到中计。','蔡瑁'],[5,'接受连环船策的统帅','为解决北兵晕船接受庞统之计。','连环'],[6,'宴江赋诗的统帅','自信锁船已稳，未采纳火攻风险的提醒。','火攻'],[7,'赤壁败逃者','火烧连营后撤退。','曹操'],[8,'华容道获释的败将','以旧恩打动关羽，被放行脱险。','云长']],
      3: [[1,'孙刘之间的调停者','引孔明见江东群臣与孙权，力主抗曹。','鲁肃'],[2,'联盟内部的沟通者','往返周瑜与孔明之间，担忧双方不和。','子敬'],[4,'借箭计划的协助者','提供船只与草束，守住孔明安排。','子敬']],
      4: [[2,'东吴抗曹将领','参与江东军事讨论，诈降计划尚未形成。','黄盖'],[4,'苦肉计执行者','与周瑜合谋，当众受杖以取信曹营。','黄盖'],[5,'诈降书的名义投降者','阚泽递交降书，计划进入取信对手阶段。','黄盖'],[7,'火船突入者','借东风与诈降接近曹军，实施火攻。','黄盖']],
      5: [[1,'刘备麾下将领','孔明指出关云长尚率精兵万人，说明刘备仍有联合抗曹的力量。','关云长'],[8,'华容道伏兵主将','立军令后仍因旧恩放曹，回营承担失令责任。','云长']],
      6: [[1,'在降战之间权衡的吴主','听群臣与孔明辩论，尚待定策。','孙权'],[2,'决定抗曹的吴主','斫案定战，将兵权交周瑜。','孙权']],
      7: [[5,'连环计献策者','以北兵不惯舟船为由劝曹操锁船，为火攻创造条件。','庞统']],
    },
    relations: {
      0: [[2,'同盟中的相忌','共同抗曹不消除周瑜对孔明才能的戒心。','孔明','strained'],[4,'限期造箭的试探落空','孔明借箭成功，周瑜不得不承认其谋略。','箭','strained'],[7,'合作破曹、各自脱身','东风助火后孔明离开吴营，联盟仍有各方利益。','孔明','strained']],
      1: [[1,'引见与调停','鲁肃为孔明引见江东主臣。','鲁肃'],[4,'借舟与守密','鲁肃提供草船所需，不向周瑜泄露安排。','子敬']],
      2: [[4,'苦肉与诈降','受杖是共同计划的一部分，并非真实决裂。','黄盖','hidden'],[7,'火攻配合','黄盖执行突入，周瑜的水军接应进攻。','黄盖']],
      3: [[5,'献策者与受计者','曹操接受锁船建议，短期稳定掩盖火攻危险。','庞统','hidden']],
      4: [[8,'旧恩压过军令','曹操提及旧恩，关羽最终放行。','云长','resolved']],
      5: [[8,'军令与恩义冲突','孔明安排华容伏兵；关羽放曹后回营受责。','军令','strained']],
      6: [[2,'君臣授兵','孙权定战，周瑜受命统军。','周瑜']],
      7: [[3,'水战与反间','周瑜在水战后借蒋干使曹营自损将领。','蒋干','strained'],[7,'赤壁火攻','黄盖突入与东风共同使曹军锁船燃烧。','火','resolved']],
      8: [[4,'借敌之箭','孔明利用浓雾与曹军谨慎收得箭支。','箭'],[8,'布置败军退路','孔明在曹操退路设伏，华容道成为最后的恩义关口。','华容']],
    },
    world: {
      0: [[3,'双方水军交锋，北军缺乏熟练水战将领的问题显露。','水军'],[5,'锁船使北兵更稳，却积累火势难隔断的危险。','连环'],[7,'东风与火船使连锁曹营陷入大火。','火']],
      1: [[1,'孙刘合作尚在争论和游说中，降曹意见仍有影响。','孙权'],[2,'抗曹决策落定；共同敌人未消除双方猜忌。','周瑜']],
      2: [[4,'浓雾、草船与曹军不敢贸然出战的判断共同完成借箭。','箭']],
      3: [[5,'庞统献策以锁船减轻北兵晕船，曹操接受。','连环'],[6,'火攻风险被提出，曹操相信季节风向足以保护船阵。','火攻'],[7,'东风突破其假设，连船使火势无法切断。','火']],
      4: [[8,'关羽为华容道任务立军令，放曹后必须承担失令责任。','军令']],
      5: [[8,'曹军退路；关羽在旧恩与军令之间选择放行。','华容']],
      6: [[5,'黄盖受刑的表象与阚泽说辞配合，使曹操相信投降。','阚泽'],[7,'诈降作为火船接近曹营的掩护得到实际运用。','黄盖']],
    },
  },
  'demo-austen': {
    characters: {
      0: [[1,'Bennet daughter favoured by her father','Her father praises Lizzy’s quickness; her own view of the new neighbour is not yet heard.','Lizzy'],[3,'Observer nursing an overheard slight','Hears Darcy call her tolerable and turns the insult into an amusing story.','tolerable'],[4,'Sister sceptical of easy praise','Questions Jane’s generous judgement of Bingley’s sisters.','Jane'],[5,'Friend whose pride has been hurt','Explains why Darcy’s pride is hard for her to forgive.','pride'],[6,'Observer unaware of Darcy’s changing opinion','Declines a dance without knowing the extent of his new interest.','dance']],
      1: [[3,'Bingley’s proud friend','Refuses local dance partners and dismisses Elizabeth within her hearing.','tolerable'],[4,'Reserved friend with influence','Bingley trusts his judgement despite their different social reactions.','judgment'],[6,'Privately interested observer','Begins to admire Elizabeth’s eyes and conversation; she does not know his changed view.','fine eyes']],
      2: [[1,'Bennet daughter mentioned in family plans','Her mother hopes the new wealthy tenant will marry one of the daughters.','Jane'],[3,'Bingley’s preferred dance partner','Dances with him twice at the assembly.','twice'],[4,'Generous judge of the newcomers','Praises Bingley and his sisters, disagreeing gently with Elizabeth.','Jane'],[6,'Woman whose reserve invites uncertainty','Charlotte thinks her affection should be made more visible.','Charlotte']],
      3: [[1,'Reported new tenant of Netherfield','A wealthy single stranger discussed as a marriage prospect; no personal meeting yet shown.','Bingley'],[2,'Neighbour visited by Mr Bennet','An introduction is now possible after Mr Bennet reveals his visit.','paid the visit'],[3,'Sociable admirer of Jane','Dances with Jane twice and enjoys the assembly.','twice'],[4,'Warm friend influenced by Darcy','His favourable opinions contrast with Darcy’s but he trusts his friend’s judgement.','Darcy']],
      4: [[3,'Miss Lucas at the assembly','Mrs Bennet reports that Bingley’s first dance was with Miss Lucas.','Miss Lucas','Miss Lucas'],[5,'Elizabeth’s pragmatic friend','Discusses the assembly and distinguishes social expectations from personal offence.','Charlotte','Charlotte Lucas'],[6,'Friend advising visible affection','Argues that Jane should not hide her preference from Bingley.','Charlotte']],
      5: [[1,'Mother planning advantageous marriages','Urges her husband to visit the new tenant and complains about her nerves.','nerves'],[2,'Mother discovering a concealed visit','Delighted when her husband reveals he has already called on Bingley.','paid the visit'],[3,'Mother delighted by Jane’s reception','Reports Bingley’s attention and Darcy’s affront in sharply different terms.','twice']],
      6: [[1,'Father teasing his household','Lets Mrs Bennet believe he is reluctant to call on Bingley.','Bennet'],[2,'Neighbour who has already made the visit','Reveals his introduction only after prolonging the family’s uncertainty.','paid the visit']],
      7: [[3,'Bingley’s sister at the assembly','Part of the fashionable Netherfield party; motives beyond the encounter remain unclear.','sisters'],[4,'Selective new acquaintance','Shows partiality toward Jane while the sisters privately look down on local society.','sisters'],[6,'Darcy’s attentive companion','Responds to his admiration of Elizabeth with mockery of her family.','fine eyes']],
    },
    relations: {
      0: [[3,'A slight overheard','Darcy’s refusal to dance wounds Elizabeth’s pride.','tolerable','strained'],[6,'Unequal knowledge of an attraction','Darcy’s interest grows; Elizabeth still reads him through the assembly insult.','fine eyes','strained']],
      1: [[3,'Visible interest','Bingley dances with Jane twice, inviting neighbours to infer a preference.','twice'],[6,'Affection and uncertain visibility','Charlotte worries that Jane’s composed manner conceals her feelings.','Charlotte']],
      2: [[4,'Affectionate disagreement','Elizabeth questions Jane’s favourable judgement of almost everyone.','Jane']],
      3: [[5,'Pride and its costs','The neighbours discuss whether Darcy has grounds for pride.','pride'],[6,'Wit meets pragmatism','Charlotte advises displaying affection; Elizabeth resists the calculation.','Charlotte']],
      4: [[3,'Contrasting social temperaments','Bingley wants Darcy to dance, while Darcy refuses.','dance'],[4,'Friendship with unequal influence','Bingley relies on Darcy’s judgement despite their differences.','judgment']],
      5: [[1,'Domestic misdirection','Mrs Bennet requests a visit while her husband teases her.','nerves','strained'],[2,'The concealed visit revealed','Mr Bennet discloses that he has already called on Bingley.','paid the visit','resolved']],
      6: [[6,'Attention and social policing','Miss Bingley mocks Elizabeth’s family after Darcy praises her eyes.','fine eyes']],
    },
    world: {
      0: [[1,'A newly rented estate whose wealthy tenant immediately changes the neighbourhood’s marriage expectations.','Netherfield'],[3,'Its party draws public scrutiny at the assembly.','Bingley']],
      1: [[1,'The Bennet home is where news of the new tenant becomes family negotiation.','Bennet'],[4,'Private conversations interpret the assembly and reveal differing judgements.','Jane']],
      2: [[1,'Mrs Bennet thinks her husband must call before the daughters can properly meet Bingley.','visit'],[2,'Mr Bennet has made the visit; the introduction is secured.','paid the visit']],
      3: [[3,'Bingley’s two dances with Jane make a preference publicly visible, without proving a future engagement.','twice']],
      4: [[1,'Reported income creates expectations before the newcomer’s conduct is known.','thousand'],[3,'Darcy’s larger fortune initially impresses the assembly, then his manners reverse its opinion.','thousand']],
      5: [[5,'The Lucas family’s home anchors neighbourly discussion of the assembly.','Lucas'],[6,'Social evenings create further occasions for Darcy and Elizabeth to misunderstand each other.','Lucas']],
    },
  },
  'demo-dracula': {
    characters: {
      0: [[1,'Solicitor travelling to a new client','Records meals, routes and unsettling local warnings on the journey to the Count’s castle.','Bistritz'],[2,'Guest discovering confinement','No reflection appears for the Count; locked doors expose that the guest is a prisoner.','prisoner'],[3,'Prisoner witnessing unnatural behaviour','Sees the Count crawl down the wall and encounters three threatening women beyond the safe rooms.','lizard'],[4,'Prisoner seeking an escape route','Forced letters, intercepted messages, stolen clothes and earth boxes confirm deliberate captivity.','letters']],
      1: [[1,'Client awaiting an English solicitor','The journey is arranged in his name; locals fear the destination. His nature is unconfirmed.','Dracula'],[2,'Host whose hospitality conceals captivity','Questions Harker about England, has no reflection and destroys the shaving glass.','glass'],[3,'Unnatural master of the castle','Crawls along the wall and asserts control over the women’s access to his guest.','lizard'],[4,'Captor manufacturing a false timetable','Dictates future-dated letters and uses Harker’s clothes; prepares earth-filled cargo for departure.','letters']],
      2: [[1,'Jonathan’s absent fiancée','Known through his thoughts and hoped-for correspondence; no independent viewpoint is shown.','Mina'],[4,'Intended reader beyond the prison','Jonathan’s hopes of reaching Mina give his record a destination outside the castle.','Mina']],
      3: [[2,'Employer invoked by the host','His letter is used to frame the visit as ordinary business.','Hawkins']],
      4: [[1,'Innkeeper’s wife offering a warning','Urges Jonathan not to travel and gives him a crucifix; he does not yet understand the danger.','crucifix'],[2,'Absent benefactor of a protective gift','The crucifix checks the Count’s sudden reaction to blood, changing Jonathan’s understanding of the warning.','crucifix']],
      5: [[3,'Three threatening inhabitants','Approach Jonathan while he sleeps outside the safe rooms; the Count intervenes and claims him.','three']],
    },
    relations: {
      0: [[1,'Client and travelling solicitor','A respectable assignment brings Jonathan toward the castle despite local warnings.','Dracula'],[2,'Hospitality becomes confinement','The shaving incident and locked doors reveal captivity.','prisoner','strained'],[3,'Possessive protection','The Count stops the women but claims exclusive control of Jonathan.','belongs','strained'],[4,'Captor and intended victim','Forced letters and failed messages deprive Jonathan of an ordinary route home.','letters','strained']],
      1: [[1,'Affection at a distance','Jonathan records details to share with Mina.','Mina'],[4,'A future reader worth surviving for','He hopes the journal or news can reach her beyond the castle.','Mina']],
      2: [[2,'Professional duty exploited','The employer’s letter helps the Count maintain the language of hospitality.','Hawkins']],
      3: [[1,'Warning and gift','Jonathan accepts the crucifix without sharing the woman’s understanding.','crucifix'],[2,'Warning acquiring meaning','The shaving incident supplies experience that changes the gift’s significance.','crucifix']],
      4: [[3,'Curiosity meets predation','Leaving the safe rooms exposes Jonathan to the three women.','three','strained']],
      5: [[3,'A contested claim','The Count prevents the women from taking his guest and asserts possession.','belongs','strained']],
      6: [[2,'Respectable business connection','An employer’s letter and property documents support the Count’s public appearance as a client.','Hawkins']],
    },
    world: {
      0: [[1,'Remote destination reached after a disturbing carriage journey; its inner rules are still unknown.','castle'],[2,'No usable exit for the guest; ordinary hospitality proves a disguise for confinement.','prisoner'],[3,'No normal household of servants; unsafe rooms contain threatening inhabitants.','servant']],
      1: [[2,'The Count casts no reflection in the shaving glass and then destroys it.','glass']],
      2: [[1,'A departure gift from a frightened local woman; Jonathan initially interprets it through his own prejudices.','crucifix'],[2,'Checks the Count during his reaction to Jonathan’s blood, providing observable protection.','crucifix']],
      3: [[1,'A dated travel journal records meals, routes and local warnings.','May'],[2,'Records contradictions in the host’s account rather than accepting his courtesy.','prisoner'],[4,'A private chronology resists the false timetable created by dictated letters.','letters']],
      4: [[4,'The Count orders letters with future dates, creating apparent evidence of Jonathan’s freedom and continued life.','letters']],
      5: [[4,'Earth-filled boxes become both hiding place and cargo, linking the closed castle to the Count’s intended journey.','boxes']],
      6: [[2,'English estate discussed in the property transaction; a respectable reason for the visit.','Carfax'],[4,'The preparations for departure connect the transaction to the Count’s control of cargo and correspondence.','England']],
    },
  },
};
